/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      // Rutas estáticas
      { source: '/', destination: '/es', permanent: true },
      { source: '/cv', destination: '/es/cv', permanent: true },
      { source: '/experiencia', destination: '/es/experiencia', permanent: true },
      { source: '/academia', destination: '/es/academia', permanent: true },
      { source: '/prensa', destination: '/es/prensa', permanent: true },
      { source: '/proyectos', destination: '/es/proyectos', permanent: true },
      { source: '/page-2', destination: '/es', permanent: true },

      // Redirecciones deterministas desde REDIRECCIONES.md
      { source: '/thesis/:slug', destination: '/es/tesis/:slug', permanent: true },
      { source: '/conference/:slug', destination: '/es/conferencia/:slug', permanent: true },
      { source: '/multimediaProject/:slug', destination: '/es/proyecto-multimedia/:slug', permanent: true },
      { source: '/blog/:slug', destination: '/es/publicacion-blog/:slug', permanent: true },
      { source: '/', destination: '/es', permanent: true },
      { source: '/experiencia', destination: '/es/experiencia', permanent: true },
      { source: '/prensa', destination: '/es/prensa', permanent: true },
      { source: '/page-2', destination: '/es', permanent: true },
      { source: '/thesis/visualizacion-de-un-campo-de-interaccion-hipertextual-en-forma-de-red-utilizando-procesos-computacionales-caso-de-estudio-graffiti-en-trenes-de-mercancia-en-norteamerica', destination: '/es/tesis/visualizacion-de-un-campo-de-interaccion-hipertextual-en-forma-de-red-utilizando-procesos-computacionales-caso-de-estudio-graffiti-en-trenes-de-mercancia-en-norteamerica', permanent: true },
      { source: '/thesis/visualization-of-a-hypertextual-interaction-field-in-the-form-of-a-network-graph-using-computational-processes-case-study-graffiti-on-freight-trains-in-north-america', destination: '/es/tesis/visualizacion-de-un-campo-de-interaccion-hipertextual-en-forma-de-red-utilizando-procesos-computacionales-caso-de-estudio-graffiti-en-trenes-de-mercancia-en-norteamerica', permanent: true },
      { source: '/thesis/el-graffiti-ha-muerto-aproximacion-sociohistorica-de-la-aparicion-y-evolucion-del-fenomeno-del-graffiti-en-la-ciudad-de-guadalajara', destination: '/es/tesis/el-graffiti-ha-muerto-aproximacion-sociohistorica-de-la-aparicion-y-evolucion-del-fenomeno-del-graffiti-en-la-ciudad-de-guadalajara', permanent: true },
      { source: '/thesis/graffiti-is-dead-sociohistorical-approach-to-the-emergence-and-evolution-of-the-graffiti-phenomenon-in-the-city-of-guadalajara', destination: '/es/tesis/el-graffiti-ha-muerto-aproximacion-sociohistorica-de-la-aparicion-y-evolucion-del-fenomeno-del-graffiti-en-la-ciudad-de-guadalajara', permanent: true },
      { source: '/paper/etiquetando-el-trazo-del-escritor-como-las-ciencias-sociales-computacionales-moldearon-mi-investigacion-sobre-graffiti-en-trenes', destination: '/es/articulo/etiquetando-el-trazo-del-escritor-como-las-ciencias-sociales-computacionales-moldearon-mi-investigacion-sobre-graffiti-en-trenes', permanent: true },
      { source: '/paper/tagging-the-writers-trace-how-computational-social-science-shaped-my-freight-graffiti-research', destination: '/es/articulo/etiquetando-el-trazo-del-escritor-como-las-ciencias-sociales-computacionales-moldearon-mi-investigacion-sobre-graffiti-en-trenes', permanent: true },
      { source: '/paper/si-la-calle-es-el-medio-la-calle-es-el-mensaje-grafiti-como-estrategia-de-comunicacion-extraoficial-en-guadalajara', destination: '/es/articulo/si-la-calle-es-el-medio-la-calle-es-el-mensaje-grafiti-como-estrategia-de-comunicacion-extraoficial-en-guadalajara', permanent: true },
      { source: '/paper/if-the-street-is-the-medium-the-street-is-the-message-graffiti-as-an-unofficial-communication-strategy-in-guadalajara', destination: '/es/articulo/si-la-calle-es-el-medio-la-calle-es-el-mensaje-grafiti-como-estrategia-de-comunicacion-extraoficial-en-guadalajara', permanent: true },
      { source: '/paper/mineria-estructuracion-visualizacion-e-interpretacion-de-redes-hipertextuales-de-instagram-sobre-graffiti-en-trenes-en-norteamerica', destination: '/es/articulo/mineria-estructuracion-visualizacion-e-interpretacion-de-redes-hipertextuales-de-instagram-sobre-graffiti-en-trenes-en-norteamerica', permanent: true },
      { source: '/paper/mining-shaping-visualizing-and-interpreting-instagram-hypertextual-networks-of-freight-train-graffiti-communalities-in-north-america-using-machine-learning-custom-models-and-graphology', destination: '/es/articulo/mineria-estructuracion-visualizacion-e-interpretacion-de-redes-hipertextuales-de-instagram-sobre-graffiti-en-trenes-en-norteamerica', permanent: true },
      { source: '/paper/y-sin-embargo-se-mueve-aproximacion-al-concepto-de-graffiti-en-transito-desde-el-graffiti-en-trenes-de-mercancia-en-la-ciudad-de-guadalajara', destination: '/es/articulo/y-sin-embargo-se-mueve-aproximacion-al-concepto-de-graffiti-en-transito-desde-el-graffiti-en-trenes-de-mercancia-en-la-ciudad-de-guadalajara', permanent: true },
      { source: '/paper/and-yet-it-moves-approach-to-the-concept-of-graffiti-in-transit-from-freight-train-graffiti-in-guadalajara', destination: '/es/articulo/y-sin-embargo-se-mueve-aproximacion-al-concepto-de-graffiti-en-transito-desde-el-graffiti-en-trenes-de-mercancia-en-la-ciudad-de-guadalajara', permanent: true },
      { source: '/paper/el-freight-graffiti-un-circuito-de-circulacion-simbolica-transnacional-oculto-en-el-margen-de-las-vias-del-tren', destination: '/es/articulo/el-freight-graffiti-un-circuito-de-circulacion-simbolica-transnacional-oculto-en-el-margen-de-las-vias-del-tren', permanent: true },
      { source: '/paper/freight-graffiti-a-transnational-symbolic-circulation-circuit-hidden-at-the-margins-of-railway-tracks', destination: '/es/articulo/el-freight-graffiti-un-circuito-de-circulacion-simbolica-transnacional-oculto-en-el-margen-de-las-vias-del-tren', permanent: true },
      { source: '/conference/reduccion-de-nodos-mediante-inferencias-de-inteligencia-artificial-usando-graphology-y-sigmajs', destination: '/es/conferencia/reduccion-de-nodos-mediante-inferencias-de-inteligencia-artificial-usando-graphology-y-sigmajs', permanent: true },
      { source: '/conference/node-reduction-through-artificial-intelligence-inferences-using-graphology-and-sigmajs-a-case-study-on-hypertextual-conversations-in-freight-train-graffiti-in-the-north-american-region', destination: '/es/conferencia/reduccion-de-nodos-mediante-inferencias-de-inteligencia-artificial-usando-graphology-y-sigmajs', permanent: true },
      { source: '/conference/uso-de-modelos-de-clasificacion-de-aprendizaje-automatico-en-la-graficacion-de-redes', destination: '/es/conferencia/uso-de-modelos-de-clasificacion-de-aprendizaje-automatico-en-la-graficacion-de-redes', permanent: true },
      { source: '/conference/use-of-machine-learning-classification-models-both-image-and-text-in-the-network-graphing-case-study-community-of-practice-among-graffiti-writers-on-freight-trains', destination: '/es/conferencia/uso-de-modelos-de-clasificacion-de-aprendizaje-automatico-en-la-graficacion-de-redes', permanent: true },
      { source: '/conference/implicaciones-de-la-perspectiva-de-las-ciencias-sociales-computacionales-en-el-analisis-de-instagram', destination: '/es/conferencia/implicaciones-de-la-perspectiva-de-las-ciencias-sociales-computacionales-en-el-analisis-de-instagram', permanent: true },
      { source: '/conference/implications-of-the-computational-social-science-perspective-in-the-analysis-of-hypertextual-conversations-on-instagram-around-freight-train-graffiti', destination: '/es/conferencia/implicaciones-de-la-perspectiva-de-las-ciencias-sociales-computacionales-en-el-analisis-de-instagram', permanent: true },
      { source: '/conference/la-ciudad-un-palimpsesto-comunicacional-el-graffiti-neoyorquino-su-capacidad-de-crear-circuito-masivo-de-comunicacion', destination: '/es/conferencia/la-ciudad-un-palimpsesto-comunicacional-el-graffiti-neoyorquino-su-capacidad-de-crear-circuito-masivo-de-comunicacion', permanent: true },
      { source: '/conference/the-city-a-communicational-palimpsest-new-york-graffiti-and-its-capacity-to-create-a-mass-communication-circuit', destination: '/es/conferencia/la-ciudad-un-palimpsesto-comunicacional-el-graffiti-neoyorquino-su-capacidad-de-crear-circuito-masivo-de-comunicacion', permanent: true },
      { source: '/conference/el-freight-graffiti-una-comunidad-imaginada-transnacional-oculta-en-el-margen-de-las-vias-del-tren', destination: '/es/conferencia/el-freight-graffiti-una-comunidad-imaginada-transnacional-oculta-en-el-margen-de-las-vias-del-tren', permanent: true },
      { source: '/conference/freight-graffiti-a-transnational-imagined-community-hidden-at-the-margins-of-railway-tracks', destination: '/es/conferencia/el-freight-graffiti-una-comunidad-imaginada-transnacional-oculta-en-el-margen-de-las-vias-del-tren', permanent: true },
      { source: '/codeProject/modelo-reconocimiento-entidades-nombradas-graffiti-hashtags', destination: '/es/proyecto-codigo/modelo-reconocimiento-entidades-nombradas-graffiti-hashtags', permanent: true },
      { source: '/codeProject/hashtag-graffiti-named-entity-recognition-model', destination: '/es/proyecto-codigo/modelo-reconocimiento-entidades-nombradas-graffiti-hashtags', permanent: true },
      { source: '/codeProject/modelo-deteccion-graffiti', destination: '/es/proyecto-codigo/modelo-deteccion-graffiti', permanent: true },
      { source: '/codeProject/graffiti-detection-model', destination: '/es/proyecto-codigo/modelo-deteccion-graffiti', permanent: true },
      { source: '/codeProject/bot-mineria-datos-instagram-idmb', destination: '/es/proyecto-codigo/bot-mineria-datos-instagram-idmb', permanent: true },
      { source: '/codeProject/instagram-mining-data-bot-idmb', destination: '/es/proyecto-codigo/bot-mineria-datos-instagram-idmb', permanent: true },
      { source: '/codeProject/interfaz-visualizacion-datos-dvi', destination: '/es/proyecto-codigo/interfaz-visualizacion-datos-dvi', permanent: true },
      { source: '/codeProject/data-visualization-interface-dvi', destination: '/es/proyecto-codigo/interfaz-visualizacion-datos-dvi', permanent: true },
      { source: '/codeProject/amoxeh-plugin-wordpress', destination: '/es/proyecto-codigo/amoxeh-plugin-wordpress', permanent: true },
      { source: '/codeProject/amoxeh-wordpress-plugin', destination: '/es/proyecto-codigo/amoxeh-plugin-wordpress', permanent: true },
      { source: '/multimediaProject/recorriendo-el-trazo-historia-interactiva-del-graffiti-en-guadalajara', destination: '/es/proyecto-multimedia/recorriendo-el-trazo-historia-interactiva-del-graffiti-en-guadalajara', permanent: true },
      { source: '/multimediaProject/recorriendo-el-trazo-interactive-history-of-the-graffiti-in-guadalajara-city', destination: '/es/proyecto-multimedia/recorriendo-el-trazo-historia-interactiva-del-graffiti-en-guadalajara', permanent: true },
      { source: '/multimediaProject/visiones-de-paz-graciela-perez-rodriguez-defensora-de-derechos-humanos', destination: '/es/proyecto-multimedia/visiones-de-paz-graciela-perez-rodriguez-defensora-de-derechos-humanos', permanent: true },
      { source: '/multimediaProject/el-graffiti-ha-muerto', destination: '/es/proyecto-multimedia/el-graffiti-ha-muerto', permanent: true },
      { source: '/multimediaProject/el-graffiti-ha-muerto-graffiti-is-dead', destination: '/es/proyecto-multimedia/el-graffiti-ha-muerto', permanent: true },
      { source: '/multimediaProject/doculoco-florencia-13-lomas-del-paraiso', destination: '/es/proyecto-multimedia/doculoco-florencia-13-lomas-del-paraiso', permanent: true },
      { source: '/mediaAppearance/aqui-estoy-la-hazana-del-graffiti-tapatio', destination: '/es/aparicion-prensa/aqui-estoy-la-hazana-del-graffiti-tapatio', permanent: true },
      { source: '/mediaAppearance/aqui-estoy-la-hazana-del-graffiti-tapatio-here-i-am-the-odyssey-of-guadalajara-graffiti', destination: '/es/aparicion-prensa/aqui-estoy-la-hazana-del-graffiti-tapatio', permanent: true },
      { source: '/mediaAppearance/cuenta-una-de-las-historias-del-grafiti-tapatio', destination: '/es/aparicion-prensa/cuenta-una-de-las-historias-del-grafiti-tapatio', permanent: true },
      { source: '/mediaAppearance/cuenta-una-de-las-historias-del-grafiti-tapatio-shares-one-of-the-stories-of-guadalajara-graffiti', destination: '/es/aparicion-prensa/cuenta-una-de-las-historias-del-grafiti-tapatio', permanent: true },
      { source: '/mediaAppearance/presentaron-el-graffiti-ha-muerto', destination: '/es/aparicion-prensa/presentaron-el-graffiti-ha-muerto', permanent: true },
      { source: '/mediaAppearance/presentaron-el-graffiti-ha-muerto-graffiti-is-dead-was-presented', destination: '/es/aparicion-prensa/presentaron-el-graffiti-ha-muerto', permanent: true },
      { source: '/mediaAppearance/graffitik-a-digitalis-bolcseszetben-dh_budapest-konferencia', destination: '/es/aparicion-prensa/graffitik-a-digitalis-bolcseszetben-dh_budapest-konferencia', permanent: true },
      { source: '/mediaAppearance/graffitik-a-digitalis-bolcseszetben-dh_budapest-konferencia-graffiti-in-the-digital-humanities-dh_budapest-conference', destination: '/es/aparicion-prensa/graffitik-a-digitalis-bolcseszetben-dh_budapest-konferencia', permanent: true },
      { source: '/blog/entrada-de-blog-prueba', destination: '/es/blog/entrada-de-blog-prueba', permanent: true },
      { source: '/blog/sample-blog-entry', destination: '/es/blog/entrada-de-blog-prueba', permanent: true },
      { source: '/blog/hola-mundo', destination: '/es/blog/hola-mundo', permanent: true },
      { source: '/blog/hello-world', destination: '/es/blog/hola-mundo', permanent: true },
      { source: '/codeProject/tejer-red-plataforma', destination: '/es/proyecto-codigo/tejer-red-plataforma', permanent: true },
      { source: '/codeProject/tejer-red-platform', destination: '/es/proyecto-codigo/tejer-red-plataforma', permanent: true },
      { source: '/codeProject/catalogo-indicios-rancho-izaguirre', destination: '/es/proyecto-codigo/catalogo-indicios-rancho-izaguirre', permanent: true },
      { source: '/codeProject/rancho-izaguirre-indicia-catalog', destination: '/es/proyecto-codigo/catalogo-indicios-rancho-izaguirre', permanent: true },
      { source: '/codeProject/las-prendas-hablan', destination: '/es/proyecto-codigo/las-prendas-hablan', permanent: true },
      { source: '/codeProject/the-garments-speak', destination: '/es/proyecto-codigo/las-prendas-hablan', permanent: true },
      { source: '/codeProject/cartografia-semantica-desapariciones', destination: '/es/proyecto-codigo/cartografia-semantica-desapariciones', permanent: true },
      { source: '/codeProject/semantic-cartography-of-disappearances', destination: '/es/proyecto-codigo/cartografia-semantica-desapariciones', permanent: true },
      { source: '/codeProject/sistema-correlacion-tatuajes', destination: '/es/proyecto-codigo/sistema-correlacion-tatuajes', permanent: true },
      { source: '/codeProject/tattoo-correlation-system', destination: '/es/proyecto-codigo/sistema-correlacion-tatuajes', permanent: true },
      { source: '/codeProject/bitacora-busqueda-wordpress-plugin', destination: '/es/proyecto-codigo/bitacora-busqueda-wordpress-plugin', permanent: true },
      { source: '/codeProject/search-logbook-wordpress-plugin', destination: '/es/proyecto-codigo/bitacora-busqueda-wordpress-plugin', permanent: true },
      { source: '/paper/mapeo-crisis-humanitaria-desapariciones-forzadas-jalisco', destination: '/es/articulo/mapeo-crisis-humanitaria-desapariciones-forzadas-jalisco', permanent: true },
      { source: '/paper/mapping-humanitarian-crisis-forced-disappearances-jalisco', destination: '/es/articulo/mapeo-crisis-humanitaria-desapariciones-forzadas-jalisco', permanent: true },
      { source: '/paper/los-vecinos-los-escritores-de-graffiti-los-politicos-y-los-reporteros-inmersos-en-una-malla-de-mediaciones', destination: '/es/articulo/los-vecinos-los-escritores-de-graffiti-los-politicos-y-los-reporteros-inmersos-en-una-malla-de-mediaciones', permanent: true },
      { source: '/paper/the-neighbors-the-graffiti-writers-the-politicians-and-the-reporters-immersed-in-a-mesh-of-mediations', destination: '/es/articulo/los-vecinos-los-escritores-de-graffiti-los-politicos-y-los-reporteros-inmersos-en-una-malla-de-mediaciones', permanent: true },
      { source: '/conference/cartografia-de-los-desaparecidos-mapeo-desapariciones-forzadas-jalisco', destination: '/es/conferencia/cartografia-de-los-desaparecidos-mapeo-desapariciones-forzadas-jalisco', permanent: true },
      { source: '/conference/cartography-of-the-missing-mapping-forced-disappearances-jalisco', destination: '/es/conferencia/cartografia-de-los-desaparecidos-mapeo-desapariciones-forzadas-jalisco', permanent: true },
      { source: '/conference/demo-de-la-herramienta-amoxeh-en-el-quinto-encuentro-de-humanidades-digitales-2021', destination: '/es/conferencia/demo-de-la-herramienta-amoxeh-en-el-quinto-encuentro-de-humanidades-digitales-2021', permanent: true },
      { source: '/conference/demo-of-amoxeh-wordpress-plugin-in-fifth-digital-humanities-encounter-2021', destination: '/es/conferencia/demo-de-la-herramienta-amoxeh-en-el-quinto-encuentro-de-humanidades-digitales-2021', permanent: true },
      { source: '/mediaAppearance/latam-journalism-review-de-sombreros-a-pantalones', destination: '/es/aparicion-prensa/latam-journalism-review-de-sombreros-a-pantalones', permanent: true },
      { source: '/mediaAppearance/latam-journalism-review-from-hats-to-pants', destination: '/es/aparicion-prensa/latam-journalism-review-de-sombreros-a-pantalones', permanent: true },
      { source: '/mediaAppearance/wired-en-espanol-activista-crea-sitio-web', destination: '/es/aparicion-prensa/wired-en-espanol-activista-crea-sitio-web', permanent: true },
      { source: '/mediaAppearance/wired-en-espanol-activist-creates-website', destination: '/es/aparicion-prensa/wired-en-espanol-activista-crea-sitio-web', permanent: true },
      { source: '/mediaAppearance/noticias-telemundo-base-datos-campo-exterminio', destination: '/es/aparicion-prensa/noticias-telemundo-base-datos-campo-exterminio', permanent: true },
      { source: '/mediaAppearance/noticias-telemundo-database-extermination-camp-jalisco', destination: '/es/aparicion-prensa/noticias-telemundo-base-datos-campo-exterminio', permanent: true },
      { source: '/mediaAppearance/france-24-en-espanol-aplicacion-las-prendas-hablan', destination: '/es/aparicion-prensa/france-24-en-espanol-aplicacion-las-prendas-hablan', permanent: true },
      { source: '/mediaAppearance/france-24-en-espanol-the-garments-speak-app-seeker-families', destination: '/es/aparicion-prensa/france-24-en-espanol-aplicacion-las-prendas-hablan', permanent: true },
      { source: '/multimediaProject/nino-remiendos-entre-calles-y-callejones', destination: '/es/proyecto-multimedia/nino-remiendos-entre-calles-y-callejones', permanent: true },
      { source: '/multimediaProject/nino-remiendos-between-streets-and-alleys', destination: '/es/proyecto-multimedia/nino-remiendos-entre-calles-y-callejones', permanent: true },
      { source: '/multimediaProject/erostrato-video-minuto', destination: '/es/proyecto-multimedia/erostrato-video-minuto', permanent: true },
      { source: '/multimediaProject/erostrato-one-minute-fiction-film', destination: '/es/proyecto-multimedia/erostrato-video-minuto', permanent: true },
    ];
  },
};

export default nextConfig;
